QAI-198 Implement Middleware API to provide all transformed bbc news news to user
Quant-NTU/persistence-middleware pull request #4
Opened 2024-10-08 20:46 UTC by karthikstar

- Created a GET endpoint which upon called, will provide user all the transformed BBC news articles.
- When GET endpoint is triggered at the middleware, it will send a GET request to ETL to get all the articles, and will return this whole set of data to the callee

User who interacts with middleware, can retrieve all transformed BBC news through a GET request.
curl -X GET http://localhost:10001/bbcnews/transformed

2024-10-09 16:15 UTC, Ivsucram requested changes

2024-10-09 16:15 UTC, Ivsucram commented on src/main/kotlin/sg/com/quantai/middleware/controllers/BbcNewsController.kt
> +@RequestMapping("/bbcnews")
This endpoint does not fully reflect the data flow. Use something like "news_headlines," then organize the data flow via functions and endpoints.

2024-10-09 16:15 UTC, Ivsucram commented on src/main/kotlin/sg/com/quantai/middleware/controllers/BbcNewsController.kt
> +class BbcNewsController {
The scope here is still News Headlines.

2024-10-09 16:15 UTC, Ivsucram commented on src/main/kotlin/sg/com/quantai/middleware/controllers/BbcNewsController.kt
> +    private val webClient: WebClient by lazy {
User a method instead of a lazy initialized object

2024-10-09 16:15 UTC, Ivsucram commented on src/main/kotlin/sg/com/quantai/middleware/controllers/BbcNewsController.kt
> +    private lateinit var etlServiceBaseUrl: String
Refactor it to "etlBaseUrl "

2024-10-09 16:15 UTC, Ivsucram commented on src/main/kotlin/sg/com/quantai/middleware/controllers/BbcNewsController.kt
> +        val etlServiceUrl = "/api/transformed-bbc-news/all"
Insert the uri directly at the webClient request

2024-10-09 16:15 UTC, Ivsucram commented on src/main/kotlin/sg/com/quantai/middleware/controllers/BbcNewsController.kt
> +                Mono.just(ResponseEntity.status(500).body("Error fetching bbc news articles: ${it.message}"))
Use or create a custom exception

2024-10-09 16:15 UTC, Ivsucram commented on src/main/kotlin/sg/com/quantai/middleware/controllers/BbcNewsController.kt
> +            .bodyToMono(Any::class.java) // Handle dynamic response type
Remove comment

2024-10-10 14:23 UTC, Ivsucram requested changes

2024-10-10 14:23 UTC, Ivsucram commented on src/main/kotlin/sg/com/quantai/middleware/controllers/NewsHeadlinesController.kt
> +    @GetMapping("/bbc_transformed/all")
The default is to have the transformed data. The origin/source of the data does not matter in the transformed data. So, this endpoint should just be called "all".

2024-10-10 14:23 UTC, Ivsucram commented on src/main/kotlin/sg/com/quantai/middleware/controllers/NewsHeadlinesController.kt
> +                throw NewsHeadlinesException("Error fetching BBC news articles: ${it.message}")
The origin/source of the data does not matter in the transformed data. So, this general error message should not specify the BBC news. 

We can have more exceptions (not necessary at this point) where we try to investigate the origin of errors. Then, we could pin point the error to BBC and assign it to a log.

2024-10-10 21:47 UTC, karthikstar commented
Requested Changes have been made.

User who interacts with middleware, can retrieve all transformed BBC news through a GET request:
curl -X GET curl -X GET http://localhost:10001/news_articles/all

2024-10-13 20:45 UTC, merged